[global]
log_level = "info"
log_dir = "C:\\Users\\Administrator\\Developer\\cat-watcher-workspace\\.logs"
log_file_name = "cat-watcher_{Date}.log"
log_rotation = "daily"
retry_count = 3
retry_interval_ms = 1000
dry_run = false
